export const FETCH_HEADLINES_BEGIN = 'FETCH_HEADLINES_BEGIN'
export const FETCH_HEADLINES_SUCCESS = 'FETCH_HEADLINES_SUCCESS'
export const FETCH_HEADLINES_FAIL = 'FETCH_HEADLINES_FAIL'

export const FETCH_NEWPAGE_RESULTS = 'FETCH_NEWPAGE_RESULTS'
