export const FETCH_HEADLINES_BEGIN = 'FETCH_HEADLINES_BEGIN'
export const FETCH_HEADLINES_SUCCESS = 'FETCH_HEADLINES_SUCCESS'
export const FETCH_HEADLINES_FAIL = 'FETCH_HEADLINES_FAIL'

export const FETCH_NEWPAGE_RESULTSFRONT = 'FETCH_NEWPAGE_RESULTSFRONT'
export const FETCH_NEWPAGE_RESULTSBACK = 'FETCH_NEWPAGE_RESULTSBACK'

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM'
export const SET_SEARCH_TYPE = 'SET_SEARCH_TYPE'
export const SET_SORT_BY = 'SET_SORT_BY'

export const CLEAR_CURRENT_HEADLINES = 'CLEAR_CURRENT_HEADLINES'
export const CLEAR_OLD_HEADLINESFRONT = 'CLEAR_OLD_HEADLINESFRONT'
export const CLEAR_OLD_HEADLINESBACK = 'CLEAR_OLD_HEADLINESBACK'
