export const FETCH_GLOBALHEADLINES_BEGIN = 'FETCH_GLOBALHEADLINES_BEGIN'
export const FETCH_GLOBALHEADLINES_SUCCESS = 'FETCH_GLOBALHEADLINES_SUCCESS'
export const FETCH_GLOBALHEADLINES_FAIL = 'FETCH_GLOBALHEADLINES_FAIL'

export const FETCH_NEWPAGE_RESULTS = 'FETCH_NEWPAGE_RESULTS'
